### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by CattopyTheWeb**
Updated index.html - fixed grammar errors and made the email to mailto:{email}

### CODE REVIEW

**Review by ExplodeC0de — APPROVED** [review]
Thanks for editing. This request is now merging

**Comment by CattopyTheWeb** [comment]
When will it be merged to the main website?

**Comment by CattopyTheWeb** [comment]
@ExplodeC0de

**Comment by ExplodeC0de** [comment]
Sorry, I forgot ttoo click the button

**Pull request merged**
